[project]
name = "llm-zoomcamp-2026-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jin Jun", email = "15855240+jwaycube@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.7.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlitesearch>=0.3.0",
    "toyaikit>=0.0.11",
]

[project.scripts]
llm-zoomcamp-2026-code = "llm_zoomcamp_2026_code:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
