[project]
name = "llm-zoomcamp-2026-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jin Jun", email = "15855240+jwaycube@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=3.7.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "sqlitesearch>=0.3.0",
    "toyaikit>=0.0.11",
]
